os: linux
dist: bionic
language: generic
before_install:
  - vboxmanage list vms

  - cat /proc/cpuinfo
  - free -m
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add - && sudo sh -c "echo deb https://download.virtualbox.org/virtualbox/debian bionic contrib >> /etc/apt/sources.list" && sudo apt-get update && sudo apt-get install build-essential gcc make linux-headers-$(uname -r) virtualbox-6.0 && sudo usermod -aG vboxusers $(whoami)

  # - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  # - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  # - sudo apt-get update
  # - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # - sudo cat /etc/docker/daemon.json
  # - sudo rm -f /etc/docker/daemon.json
  # - sudo systemctl restart docker
  - mkdir ~/.baker
  # - sudo apt-get install bridge-utils mkisofs
  # - git clone https://github.com/ottomatica/slim.git
  # - cd slim && npm link
  # - slim build images/alpine3.8-simple
  # - slim run micro alpine3.8-simple
  # - slim vms

  - npm install -g ssmirr/bakerx
  - bakerx pull cloud-images.ubuntu.com bionic
  - bakerx run bio bionic --ip 192.168.33.10
  - export ssh_cmd=$(bakerx ssh-info bio)
  - $ssh_cmd whoami
  - vboxmanage list vms
