name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test virtualbox and VT
      continue-on-error: true
      run: |
        sysctl -a | grep machdep.cpu
        # free -m
        vm_stat
        df -h
        # cat /proc/cpuinfo
        sudo spctl --master-disable
    - name: Setup vbox
      continue-on-error: true
      run: |
        sudo spctl kext-consent disable
        brew cask install virtualbox --verbose --debug
    - name: Setup vbox
      continue-on-error: true
      run: |
        ls -al
        pwd
    - name: Setup vbox
      continue-on-error: true
      run: |
        chmod +x ./accept.sh
        sudo ./accept.sh
    - name: Setup vbox
      continue-on-error: true
      run: |
        sudo ./accept.sh
    - name: Setup vbox
      continue-on-error: true
      run: |
        sudo ./accept.sh
    - name: Setup vbox
      continue-on-error: true
      run: |
        brew cask reinstall --force virtualbox
        brew cask doctor
        # sudo apt-get update && sudo apt-get install virtualbox
        vboxmanage list vms
