name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: vboxmanage list vms
    - name: Run a multi-line script
      run: |
        sudo npm install -g ottomatica/bakerx
        sudo npm install -g opunit
