name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: vboxmanage list vms
    - name: Run a multi-line script
      run: |
        vboxmanage --version
        sudo npm install -g ottomatica/bakerx
        sudo npm install -g opunit
        bakerx pull cloud-images.ubuntu.com bionic
        bakerx run bio bionic --ip 192.168.33.10
        export ssh_cmd=$(bakerx ssh-info bio | tr -d '"')
        $ssh_cmd whoami
        vboxmanage list vms
        bakerx delete vm bio
