name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Test virtualbox and VT
      continue-on-error: true
      run: |
        sysctl -a | grep machdep.cpu
        free -m
        df -h
        # cat /proc/cpuinfo
        sudo spctl --master-disable
        brew cask install virtualbox --verbose --debug
        brew cask doctor
        # sudo apt-get update && sudo apt-get install virtualbox
        vboxmanage list vms
